name: CI/CD Pipeline

on:
  push:
    branches:
      - Silton
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v3

    # Instalar Docker e Docker Compose
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Instalar Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -L https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verifica se o docker-compose foi instalado corretamente
    
    # Instalar dependências do backend
    - name: Instalar dependências do backend e testar
      run: |
        cd api  # Entrar no diretório 'api' se o package.json está lá
        npm install
        npm test
    
    # Instalar dependências do frontend (se necessário)
    - name: Instalar dependências do frontend
      run: |
        cd blog-frontend  # Entrar no diretório 'blog-frontend' se necessário
        npm install

    # Construir as imagens Docker
    - name: Construir as imagens Docker
      run: |
        docker-compose -f docker-compose.yml build

    # Deploy no Docker Hub
    - name: Deploy no Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-professores:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/blog-professores:latest

